import { Router } from 'express'; import { z } from 'zod'; import { Event } from '../models/Event.js'; import { Venue } from '../models/Venue.js'; import { Show } from '../models/Show.js'; import { authenticate,allowRoles } from '../middleware/auth.js';
const router=Router();
router.get('/events',async(req,res,next)=>{try{const filter=req.query.type?{type:req.query.type}:{ };res.json({events:await Event.find(filter).sort({createdAt:-1})});}catch(e){next(e);}});
router.get('/events/:id',async(req,res,next)=>{try{const event=await Event.findById(req.params.id);if(!event)return res.status(404).json({error:'Event not found.'});res.json({event,shows:await Show.find({event:event._id}).populate('venue')});}catch(e){next(e);}});
router.get('/venues',authenticate,allowRoles('ADMIN','ORGANISER'),async(req,res,next)=>{try{res.json({venues:await Venue.find().sort({name:1})});}catch(e){next(e);}});
router.post('/events',authenticate,allowRoles('ORGANISER','ADMIN'),async(req,res,next)=>{try{const x=z.object({title:z.string().min(2),type:z.enum(['MOVIE','CONCERT']),description:z.string().optional()}).parse(req.body);res.status(201).json({event:await Event.create({...x,organiser:req.user.id})});}catch(e){next(e);}});
router.post('/venues',authenticate,allowRoles('ADMIN'),async(req,res,next)=>{try{const x=z.object({name:z.string().min(2),address:z.string().optional(),seats:z.array(z.object({seatId:z.string().min(1),row:z.string().optional(),number:z.string().optional(),category:z.string().min(1)})).min(1)}).parse(req.body);if(new Set(x.seats.map(seat=>seat.seatId)).size!==x.seats.length)return res.status(400).json({error:'Seat IDs must be unique.'});res.status(201).json({venue:await Venue.create(x)});}catch(e){next(e);}});
router.post('/shows',authenticate,allowRoles('ORGANISER','ADMIN'),async(req,res,next)=>{try{const x=z.object({eventId:z.string(),venueId:z.string(),startsAt:z.string(),pricing:z.record(z.number().positive())}).parse(req.body);const startsAt=new Date(x.startsAt);if(Number.isNaN(startsAt.valueOf())||startsAt<=new Date())return res.status(400).json({error:'Show start time must be a valid future date.'});const event=await Event.findById(x.eventId),venue=await Venue.findById(x.venueId);if(!event||!venue)return res.status(404).json({error:'Event or venue not found.'});if(req.user.role!=='ADMIN'&&String(event.organiser)!==req.user.id)return res.status(403).json({error:'Insufficient permissions.'});const seats=venue.seats.map(s=>({...s.toObject(),price:x.pricing[s.category]}));if(seats.some(s=>!s.price))return res.status(400).json({error:'Every seat category needs a price.'});res.status(201).json({show:await Show.create({event:event._id,venue:venue._id,startsAt,seats})});}catch(e){next(e);}});
router.get('/organiser/events/:eventId/summary',authenticate,allowRoles('ORGANISER','ADMIN'),async(req,res,next)=>{try{const event=await Event.findById(req.params.eventId);if(!event)return res.status(404).json({error:'Event not found.'});if(req.user.role!=='ADMIN'&&String(event.organiser)!==req.user.id)return res.status(403).json({error:'Insufficient permissions.'});const shows=await Show.find({event:event._id});const ids=shows.map(s=>s._id);const {Booking}=await import('../models/Booking.js');const bookings=await Booking.find({show:{$in:ids},status:'CONFIRMED'});res.json({bookingCount:bookings.length,revenue:bookings.reduce((n,b)=>n+b.seats.reduce((a,s)=>a+s.price,0),0)});}catch(e){next(e);}}); export default router;
